version: "3.9"
services:
  app:
    container_name: ProductService
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ./Dockerfile
  ports:
    - "8085:8085"
  volumes:
    - "./:/app/app"